nicolo-ribaudo/jest-light-runner

- README.md
- src/worker-runner.js
Prettier added these when using this module. 
https://github.com/prettier/prettier/tree/next/tests/config/jest-light-runner
> Add support for `setupFiles` and `snapshotSerializers`

- src/global-setup.js
- src/worker-runner.js
This PR aims to add support for `jest.clearAllMocks` and `jest.resetAllMocks`.
Fixes #18 
Thanks for [hinting me](https://github.com/nicolo-ribaudo/jest-light-runner/issues/18#issuecomment-1101449323) where to change. I tried this, and I'm facing a small issue.
I could have done like this in the `global.setup.js`:
```js
// excerpt
globalThis.jest = {
fn: mock.fn,
spyOn: mock.spyOn,
clearAllMocks: mock.JestMock.clearAllMocks.bind(mock.JestMock),
// ...
};
```
But the `jest-mock` package seem not exporting the `JestMock` instance. So I can't do `mock.JestMock.<thing>`.
https://github.com/facebook/jest/blob/d2f3dc694d72c0208f47fc2e2ca101e26a9a6d68/packages/jest-mock/src/index.ts#L1239-L1243
Could someone help?
> Add support for `jest.clearAllMocks` and `jest.resetAllMocks`

- README.md
- package.json
- src/worker-runner.js
Prettier added this option in https://github.com/prettier/prettier/pull/12612 by @SimenB 
(Maybe Babel can also use it?)
I've tested locally, it works.
//cc @SimenB
> Support `snapshotFormat`

- package.json
- src/global-setup.js
- yarn.lock
Fixes #28
~I haven't test~, but seems this is how it works. https://github.com/facebook/jest/blob/bb0956589f9dbddcc13db0f42b2d4d9ff642b2cd/packages/jest-expect/src/index.ts#L35
Tested, it works.
> Support `expect.addSnapshotSerializer()`

- src/global-setup.js
We use it to restore all mocked functions in `afterEach`
> Expose jestMock.restoreAllMocks from global setup

- src/worker-runner.js
This PR fixes issue #43, it selectively runs the "before" and the "after" hooks separately, before and after the test itself is executed. We've had this running for a while in a medium sized codebase, and it's worked well for us so far!
> Run `beforeEach`/`afterEach` in the correct order

- .gitignore
- src/worker-runner.js
`describeBlock` should not be skipped.
e.g.
`yarn jest babel-cli -t "dir --out-dir --watch multiple dir"`
> fix: filter tests

- README.md
You can reproduce the problem by cloning [ts-node-repros/jest-light-runner](https://github.com/TypeStrong/ts-node-repros/tree/jest-light-runner/) and running `ts-node --esm node_modules/.bin/jest` instead of `NODE_OPTIONS='--loader ts-node/esm' jest`.
> Recommend NODE_OPTIONS for ESM loaders

- src/worker-runner.js
[It's expected by `jest-image-snapshot`](https://github.com/americanexpress/jest-image-snapshot/blob/63dc4b51f85573d33e151959532ce1c3da48abc0/src/index.js#L172-L174).
> Add `testPath` to test state

- .github/workflows/e2e-tests.yml
- src/worker-runner.js
When calling `expect.addSnapshotSerializer` in one test file, the serializer should not be used globally.
Solution verified in https://github.com/prettier/prettier/pull/12859
Fixes #35
> Fix `addSnapshotSerializer`

- .github/workflows/e2e-tests.yml
It's failing because prettier specifies `--runInBand`
> Don't run prettier with workers

- src/worker-runner.js
Fixes https://github.com/babel/babel/pull/14867#issuecomment-1221608605
@fisker Do you use inline snapshots in Prettier, and if yes did you ever had problems with the `-u` Jest options not working?
> Error locations are already converted from URLs to paths by Jest

- src/worker-runner.js
The `expect` is not declared in `package.json` anyway. Since we already imported `@jest/expect`, we use `jestExpect` in the worker runner, too.
> use @jest/expect in worker-runner

- README.md
According to the [readme of cross-env](https://github.com/kentcdodds/cross-env/blob/3edefc7b450fe273655664f902fd03d9712177fe/README.md):
> Pay special attention to the **triple backslash** `(\\\)` **before** the **double quotes** `(")` and the **absence** of **single quotes** `(')`. Both of these conditions have to be met in order to work both on Windows and UNIX.
I’ve experienced this on a Window machine before and can confirm that `'` doesn’t work within `cmd.exe`, while `"` does. The former breaks command execution with an error.
As a result, attention is needed when adding a test script to `package.json`, as the double quote needs to be escaped in JSON:
```json
{
"scripts": {
"test": "cross-env NODE_OPTIONS=\"--loader ts-node/esm\" jest"
},
}
```
> docs(readme): use double quotes for Windows compat

- package.json
- src/global-setup.js
- yarn.lock
I'm testing this in Babel, it looks like there is a Node.js bug but I'm updating it here to simplify testing.
@fisker Could you try if it causes any problem in Prettier?
cc @SimenB
> Use Jest 30.0.0-alpha.1

- .github/workflows/e2e-tests.yml
- package.json
- src/index.js
- src/worker-runner.js
- yarn.lock
> Replace `piscina` with `tinypool`

- src/index.js
@fisker You're right, it can destroy processes when idle, which leads to inaccurate coverage.
This PR fixes it, and the tests will be slightly faster. :)
> fix: Coverage not accurate on child_process runner

- src/index.js
Didn't notice it's already done in worker https://github.com/nicolo-ribaudo/jest-light-runner/blob/c47d1baefd7ce80c25b41290582a6a173b5e69ec/src/worker-runner.js#L265
> Remove `determineSlowTestResult`

- .yarnrc.yml
- src/index.js
- src/worker-runner.js
- Only pass `projectConfig` once
- in workers use `workerData`
- in main thread, use named export `setWorkerData`
- in child process, use `channel`
- Only override `cwd` and `chdir` in worker
- Unset env in main thread
> Reduce data transferring

- README.md
- src/index.js
When config with multiple projects with the same runner, before #98 it will use wrong project config since we only init once, in #98 we refuse to run https://github.com/nicolo-ribaudo/jest-light-runner/blob/aafa92631fe4e64c2f0b5fb6233d3482b1a522dc/src/index.js#L41
> Support multiple projects with same runner

- src/worker-runner.js
I'm not sure under which circumstances this exactly goes wrong, but this fixes a difference in behaviour that I observed between the upstream Jest runner and this runner.
A test file that worked with the upstream runner would error out with the following message:
Snapshot state must be initialized
Snapshot state has value: undefined
Initializing the snapshot state before loading the tests fixes this.
> Initialize snapshot state before loading tests
